### ISSUE TITLE
Remove FFTConvolution class

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-ops#12]
The FFTConvolution class was copied from ImgLib2 wholesale. This class was taken from `imglib2-algorithms-gpl`, which is licensed under the GPL. Hence, this class is incompatible with ImageJ OPS's BSD-2 licensing.

To address this issue in the short to medium term, we can split the `imagej.ops.convolve` package into its own component, `ij-ops-gpl`, which depends on `imglib2-algorithms-gpl`. But ideally, we don't want any part of OPS to be licensed under the GPL; better would be to find a way to do convolution without that code.

See also https://github.com/imglib/imglib/issues/61

**Comment by ctrueden** [comment]
@dietzc and I are reviewing all the issues. What is left to do to close out this issue? We have to:

* Delete `FFTConvolution` from `imagej-ops` in favor of a new JTransforms-based `FFTConvolution` which will exist in `imglib2-algorithm-fft` which is BSD-2 licensed.
* Update `ConvolveFourier` to use the new `FFTConvolution` from `imglib2-algorithm-fft`.

Is that right?

Alternately, the whole `imglib2-algorithm-fft` project could just merge to `imagej-ops`. What do others think?

**Comment by bnorthan** [comment]
Hi @ctrueden 

ConvolveFourier is no longer used, the new convolve is called ConvolveFFTImg.  FFTConvolution is not used anymore either.   

You should be able to just delete the following two files

Delete FFTConvolution from imagej-ops
Delete ConvolveFourier from imagej-ops

We should probably still get permission from @StephanPreibisch to relicense.  There is a class https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/fft/filter/CreateFFTFilterMemory.java that reused a section of his code for the FFT memory handling. 

The issue with imglib2-algorithm-fft was different as the problem was the jdk-mines license.

**Comment by ctrueden** [comment]
Thanks @bnorthan! Maybe you could discuss the licensing along with https://github.com/imglib/imglib2-algorithm-fft/pull/3 when you meet with @StephanPreibisch in person.
