### ISSUE TITLE
Simple RAI to II Converter causes problems in several tests

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#126]
Hi @ctrueden @hinerm @bnorthan,

@tibuch wrote a nice little SciJava-Converter from `RandomAccessibleInterval` to `IterableInterval` (see https://github.com/imagej/imagej-ops/commit/829d9e9d2e83cf20aa5638592626b75754e0eb51). This converter causes problems in several UnitTests. From my point of view, the failing of the tests is correct, as now several plugins with same priority can be discovered. However, I'm not 100% sure how to fix this issue, especially in the `FFT` framework. Maybe you can have a look and fix the tests on the https://github.com/imagej/imagej-ops/tree/scijava-converters branch?!

Thanks! Christian

PS: @tibuch and me will implement several further converters these days and let you know if additional tests start to fail.

**Comment by bnorthan** [comment]
@dietzc The convolve and deconvolve tests are now passing.   Once you finalize the converters I'll take another look to ensure that the FFT framework design still makes sense.

**Comment by hinerm** [comment]
Hi @dietzc and @tibuch 

When a `Converter` is created it's telling the conversion framework "If something is requesting this output type, and I have this input type, then I can satisfy that request".

Typing the `convertRAItoII` on `RandomAccessibleInterval, IterableInterval` is thus too permissive to rely solely on default type matching logic, as you can not freely interchange `IterableInterval` and `RandomAccessibleInterval` subclasses.

For example, one of the unit tests is failing because it tries to call the `Add` op to add a constant to a `PlanarImg`. There are many `AddConstant` implementations, e.g. to add to an `ArrayImg` or a `PlanarImg`. Op matching tests an `ArrayImg` candidate first, says "Oh this will match because I can convert `PlanarImg` to `ArrayImg` using `convertRAItoII`", and then explodes because the result of that conversion is still a `PlanarImg` which can not be assigned to the `ArrayImg` input.

One solution would be to override the [`canConvert`](https://github.com/scijava/scijava-common/blob/scijava-common-2.41.0/src/main/java/org/scijava/convert/Converter.java#L197) method to ensure you only return true if the conversion is actually legitimate. I am not sure what that would entail.

P.S. Not sure where you intended this converter to end up, but they should be in the component that makes the most sense given their parameters. In this case, the `convertRAItoII` should go in [imagej-common](https://github.com/imagej/imagej-common) as that is the lowest level ImageJ component with an ImgLib2 dependency.

**Comment by hinerm** [comment]
@dietzc OK, @ctrueden and I talked more about this and there is probably also a bug in the default `Converter` behavior... so hopefully you won't need to do any special implementation of `canConvert`

**Comment by ctrueden** [comment]
Yes, I think in the vast majority of cases, it will not be necessary to override `canConvert`. We found a really serious bug in the default implementation of `canConvert`, where it was matching destination types that were not actually compatible with the request. Fixing that bug resolved the issue.

**Comment by hinerm** [comment]
[fixed](https://github.com/scijava/scijava-common/commit/3dfe6f379d464137726d341b49ed16afea945646)

**Comment by dietzc** [comment]
thanks a lot guys. one bug less... we will implement more converters :+1:
