### ISSUE TITLE
Improve Op Namespace Categorization 

### ISSUE THREAD

**Issue by awalter17** [imagej/imagej-ops#146]
It would be beneficial to create more namespaces and have better organization for the current ops.

Here are some of my proposed changes:
* New statistics namespace 
* Change deconvolve name space to Convolve and include both deconvolution and convolution ops in there
  * I can't really think of a good/clear name for such a namespace though 
* New Fourier namespace 
  * Could we potentially group Fourier and Convolve together?
* Move threshold op from Global to ThresholdNamespace 
* New Trig namespace for Circular functions
* New Hyperbolic namespace for Hyperbolic functions 
  * is there a way to group the Hyperbolic and Circular functions in one namespace?

Here's the google spreadsheet that summarizes all of the proposed changes: https://docs.google.com/spreadsheets/d/1bmKtVZXci9KVshfLk_5rKa-nlVv1DW39aQxYA9nsLdI/pubhtml

Feel free to add changes to the google spreadsheet, but please leave a comment if you make a change. Also please let me know your thoughts on my proposed changes/additions.

Thank you in advance for your contributions!

**Comment by ctrueden** [comment]
Thanks for starting this conversation, @awalter17! It's definitely time to organize the ops better. And as soon as #145 is merged (working on that now!), and we agree on the details of this issue, we can shuffle everything around.

Firstly, a couple of comments while wearing my OPS dictator hat:

* Op names and namespaces are written using lower camel case.
* Op and namespace names should be kept as concise as possible. Keep in mind that the Java code will typically look something like: `ij.op().trig().cos(a)`. Overly verbose names make it harder to read. So in general, we should use the shortest reasonable abbreviation for each concept—and also lean toward names with such suitable abbreviations.
* As a rule of thumb, the OPS design tries to follow Java conventions where possible.
* The `createImg` op listed in the spreadsheet is out of date with the master branch. There are probably other minor discrepancies, which we will update next week after the merge of #145.

The rest of my comments are just my personal preference (i.e., dictator hat off). These are intended to spur discussion, rather than mandate anything. So flame on, folks! Everyone loves naming discussions, right @LeeKamentsky? I know at least @dietzc, @bnorthan, @hinerm and @tpietzsch will eat this up. :cake: 

* Personally I lean toward keeping the trigonometric and hyperbolic functions in the math namespace, even though it is a long list. I see no good "hyperbolic" abbreviation, and it is a small set of functions anyway. I also think people are used to seeing all those functions in "math" already thanks to `java.lang.Math`.
* Should we have a `thread` namespace for things like `chunker`?
* I like the statistics namespace, but would suggest calling it `stats`. And I think `histogram` and `normalize` belong in there.
* There are additional things in global that I feel should be moved out—e.g., `gauss`, `gaussKernel` and `logKernel`, though I am not sure where without digging in to those ops in more detail.
* There are some things in `math` that I think don't belong there: `addNoise`, `gaussianRandom` and `uniformRandom`.
* The `threshold` op (currently in global) should be renamed to something like `apply` with its move into the `threshold` namespace.
* For some of the image-centric operations, maybe an `image` namespace? E.g.: `project` and `scale`.
* It also seems like there could be a namespace for all the "meta-ops" which operate on functions (e.g., `map` and `slicewise`), but perhaps global is the best place for such things (writing `ij.op().meta().map(...)` might be too unintuitive).

**Comment by hinerm** [comment]
>Should we have a thread namespace for things like chunker?
>writing ij.op().meta().map(...) might be too unintuitive

Mixed feelings here. Conceptually I like the idea of categorizing meta operations like this... but I do think it adds some unnecessary complexity, so I'm leaning towards voting to keep all of these functions in `global`.

>Personally I lean toward keeping the trigonometric and hyperbolic functions in the math namespace

:+1: 

>Could we potentially group Fourier and Convolve together?

I feel like there isn't a perfect namespace label that covers convolution and deconvolution, but their close relationship makes grouping these together worthwhile. Maybe in an `xform` namespace, as that would also fit `Fourier`.

>e.g., gauss, gaussKernel and logKernel, though I am not sure where without digging in to those ops in more detail.

* `gauss` goes in `xform` since it's a convolution
* `gaussKernel` & `logKernel`: I believe these are making kernels for use in transformational operations like convolution. So I would also put them in `xform`... or maaaaybe a dedicated `kernel` namespace if we think multiple namespaces will be consuming these. 

> addNoise

Also belongs in `xform` since this is effectively performing convolution.

> gaussianRandom and uniformRandom

`math` namespace seems OK since these are just generating random values.

>maybe an image namespace

Makes sense to me.

**Comment by ctrueden** [comment]
> > `gaussianRandom` and `uniformRandom`
> `math` namespace seems OK since these are just generating random values.
Fair enough! There is a `Math.random()` function, after all. Then my preference would be to rename these to `randomGaussian` and `randomUniform`, since go together. I would also be fine with a dedicated `random()` namespace.

I like the `xform` namespace—unless someone can think of a more intuitive name?

**Comment by hinerm** [comment]
>unless someone can think of a more intuitive name?

Impossible! So says [the internets](http://acronyms.thefreedictionary.com/transformation)

**Comment by hinerm** [comment]
>randomGaussian and randomUniform

:+1:

**Comment by ctrueden** [comment]
OK, I renamed `uniformrandom` and `gaussianrandom` to `randomUniform` and `randomGaussian` on the master branch: 14eca9dc8e984d75aa9d04a49acdca8e1d30baa9

**Comment by bnorthan** [comment]
I'm not sure it makes sense to group Fourier and Convolve and noise together.  Not all convolutions use Fourier Transforms.   Noise might fit in better with the stats namespace.

I was just looking at the current ImageJ menu structure for fft, filters, noise and deconvolution (My initial thought is that it would sense to follow a similar organization for ops name spaces). 

* There is a menu for fft related operations with 8 options (FFT, Inverse FFT, Power Spectrum etc.)
* There is another menu for filters with almost 20 options (Convolve, Gaussian Blur, Mean, Median etc.)
* There is a noise menu 
*  There is no currently no deconvolution menu, but typically the deconvolution plugins have several  options, for example DeconvolutionLab has 6 different types of deconvolution

**Comment by ctrueden** [comment]
@bnorthan Cool, so you'd suggest corresponding namespaces `fft` (or `fourier`?), `filter`, `noise` and `decon` then?

**Comment by bnorthan** [comment]
Yes.  I think it would make sense to have those corresponding name spaces.

**Comment by awalter17** [comment]
So I've tried to update the google doc to reflect the discussion that was happening here, but if I missed any changes or misinterpreted any of the suggestions please let me know!

**Comment by ctrueden** [comment]
Any further comments from anyone? If not, @awalter17 and I will go to town on the renames over the next couple of weeks.

**Comment by dietzc** [comment]
I would like to add two more namespaces to the mix: 

* `FilterNamespace` which contains all kind of filters (`Gauss`, `DoG`, `LoG` etc) which of course may base on e.g. `Convolve` operations.

* `LabelingNamespace` which comprise all operations which produce or can handle an `ImgLabeling` (for example `CCA`).

Does this make sense?

**Comment by ctrueden** [comment]
@dietzc Yep, `filter` and `labeling` make sense. Right now the spreadsheet shows `convolve` becoming `filter.convolve`. Any other existing ops that should go into the `filter` namespace?

As for `labeling`, we have no such ops yet (`DefaultCreateImgLabeling` will go in `create.labeling`, OK?). But when we do, makes sense.

**Comment by ctrueden** [comment]
OK, the first pass of op organization is complete. The global namespace has been trimmed down to a much more reasonable level. The following namespaces now exist:

* create
* deconvolve
* filter
* image
* labeling
* logic
* math
* stats
* thread
* threshold

I know we talked about having an `fft` namespace but it bothered me that there would then be `fft.fft` and `fft.ifft` ops. For now, I put all these related ops into the `filter` namespace: `filter.addNoise`, `filter.convolve`, `filter.correlate`, `filter.fft`, `filter.fftSize`, `filter.gauss` and `filter.ifft`. I think it reads rather nicely but if others do not like it, we can reevaluate and do another naming pass.

Package names are now also much more consistent. In general, the pattern is: `net.imagej.ops.<ns>.<op>` where `<ns>` is the namespace name and `<op>` is the op name. I eliminated other superfluous/inconsistent subpackages in favor of this scheme wherever possible.

I also made the base op interfaces consistent—they all live in `net.imagej.ops.Ops`, autogenerated from the `Ops.list`/`Ops.vm`.

This makes it much easier to find code of interest; e.g., the `ops.image().ascii(...)` methods call ops defined in the `net.imagej.ops.image.ascii` package that implement `Ops.Image.Ascii`.

The main thing left to do relating to renames is to move the `convert` ops out of global and into their own namespace. @awalter17 is currently working on the `convert-ops` branch which will add many more ops to that namespace, so we can tackle it as part of that work.

Therefore, I close this issue as resolved! But please feel free to reopen, and/or open a new issue, for any remaining naming issues or disagreements.
