### ISSUE TITLE
Generalize OutputOp and InputOp?

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#149]
Hi all,

I ran into a situation where I would like to split or extend `OutputOp` and `InputOp`. `OutputOp` should extend `OutputGet` and `OutputSet` as in some situations you only want to use one of these interfaces instead of `OutputOp`. Also many implementations do only need a `OutputGet`.

Example: While implementing `View` wrappers, we recognized that we could certainly implement a `OutputGet` in a `View` but not really a `OutputSet` as setting the output doesn't make sense for a `View` in general. Actually, for all `Op`s and especially for `Computer`s `OutputGet` makes sense, this means for `Op`s which output is really not `Type.Both`. 

If we agree that this makese sense and also agree on a nice naming scheme, I'm happy to file a PR.

**Comment by ctrueden** [comment]
The main use case is for "read-only" `OutputOp` implementations, correct? (I.e.: there is no "write-only" use case?) You could accomplish that at the moment by making `setOutput` simply `throw new UnsupportedOperationException()`. Would that be sufficient?

> Actually, for all `Op`s and especially for `Computer`s `OutputGet` makes sense, this means for `Op`s which output is really not `Type.Both`. 

I was recently talking to @awalter17 about a related issue: in OPS, the social contract of `Function` ops is that the have a `BOTH` output. There is no `PureFunction` or similar that has an `OUTPUT` output in cases where it passing in a preallocated output would not make sense.

Yes, there is `Computer` now, which has the `O compute(I in)` method. But the design of the `Function` type hierarchy seems a little strange to me since it cannot accommodate a `PureFunction` which has an `OUTPUT` output:

| interface | output type | output optional? | setOutput | createOutput | compute(I) | compute(I, O) |
| --- | --- | --- | --- | --- | --- | --- |
| `Function` | - | - | yes | no | no | yes |
| `OutputFunction` | BOTH | yes | yes | yes | yes | yes |
| `InplaceFunction` | BOTH | no | yes | no | yes | yes |
| `AbstractStrictFunction` | BOTH | no | yes | yes | no | yes |
| `PureFunction` (proposed) | OUTPUT | N/A | no | no | yes | no |

Is it worth adding another superinterface of `Function` just so that `PureFunction` can extend it? The names are getting pretty unintuitive. Perhaps we should rename `Function` to something else (`ImpureFunction`?) and then have `Function` be the superinterface of `PureFunction` and `ImpureFunction`? But if we did that, all the existing stuff that uses `Function` (e.g., `Map` implementations) would all take `ImpureFunction`s as input. And `Function` itself would have neither `compute(I)` nor `compute(I, O)`. Would that be more or less confusing?

**Comment by ctrueden** [comment]
Another possibility then might be to consolidate `Op` and `Function`. And get rid of the `Function` thing altogether: instead we would have `Op`, extended by `PureOp` and `ImpureOp`, the latter extended by `InplaceOp` and `StrictOp` and `OutputOp`.

Do we have any legitimate use cases for ops which _cannot_ be reasonably shoehorned into the `PureFunction` or `ImpureFunction` patterns? Every `Op` should really be able to be made `Threadable` I think. If not, it's a pretty sloppy op.

**Comment by dietzc** [comment]
> The main use case is for "read-only" OutputOp implementations, correct? (I.e.: there is no "write-only" use case?) You could accomplish that at the moment by making setOutput simply throw new UnsupportedOperationException(). Would that be sufficient?

This is certainly a solution, yes. I had this in mind, too. At the moment, I don't see any problems, but I'm not entirely convinced that there won't be any in the future.

About `Function`s: I agree, the interface hierarchy is confusing and the `Computer` actually is a `PureFunction`. However, there is one more relation which comes to my mind. Each `OutputFunction` is actually a `PureFunction`.  So what about the following:

Top-Level: `Op`. `Function` actually has a `O compute(I input)`. `ImpureFunction` actually has a `O compute (I input, O output)`. They live side by side. And we actually have nothing else.

We could get rid of `OutputFunction` (which is a `Function` now) and `Computer`. We also can get rid of `StrictFunction` because each `Function` is strict implicitly. So if you pass `null` to a `ImpureFunction` which is not a `Function`, the algorithm will fail. So the contract for `ImpureFunction` is that, no matter what, the output has to be non-null and provided. If the an `Op` knows how to create the output, it is additionally a `PureFunction`.  Does this make sense? `InplaceFunction` implements only  interfaces. 

About the naming: What about having a `FunctionalOp` and something like a `DumbFunctionalOp` (which is a horrible name).

**Comment by dietzc** [comment]
Also: We could keep in mind (or directly use it?) that we may want to make use of the `Function`s stuff of Java 8. Of course this depends on the plans with ImageJ2 and Java8.

**Comment by ctrueden** [comment]
As discussed earlier today, I'll do some redesign of the `Function` type hierarchy. I think we probably don't need `OutputSet` and `OutputGet` separately, but I'll think about it during the redesign.

**Comment by ctrueden** [comment]
Thanks for your comments and insight, @dietzc.

I very briefly looked at the Java 8 `Function` documentation and from what I gather, it will be compatible with the appropriate interfaces here—once OPS requires Java 8, we can implement the appropriate interfaces to make these ops usable with lambdas, at least to a certain extent. However, I didn't dig too deep yet—I had to stop reading before my brain imploded after coming across gems like: `the compiler will treat any interface meeting the definition of a functional interface as a functional interface`.

Anyway, here is a proposed design, similar to your ideas above:
```java
/** An {@code Input} is an object with an associated typed input field. */
public interface Input<I> {
  void setInput(I);
  I getInput();
}

/**
 * An {@code Output} is an object with an associated typed output field. In
 * general, no API is provided to set the output reference, since the
 * feasibility of such an operation depends on the implementation.
 */
public interface Output<O> {
  O getOutput();
}

/**
 * An object with a typed input and typed output fields.
 * @see Input
 * @see Output
 */
public interface InOut<I, O> extends Input<I>, Output<O> { }

/**
 * A <em>function</em> computes a result from the given input, returning it as
 * a new object. The contents of the input are not affected.
 */
public interface Function<I, O> extends InOut<I, O> {
  O compute(I);
}

/**
 * A <em>computer</em> calculates a result from the given input, storing it
 * into the specified output reference.
 */
public interface Computer<I, O> extends InOut<I, O> {
  void compute(I, O);
}

/**
 * An <em>inplace</em> operation is a {@link Computer} whose input and output
 * are the same object. In other words: the given input object is mutated.
 */
public interface Inplace<A> implements Computer<A, A> {
  void compute(A);
}

/**
 * A <em>hybrid</em> operation can be used as either a {@link Function} or as a
 * {@link Computer}. To compute a new output object, call {@link
 * Function#compute}; to populate a preexisting output object, call {@link
 * Computer#compute}.
 */
public interface Hybrid<I, O> implements Function<I, O>, Computer<I, O> {
  O createOutput(I input);
}

// And now: a bunch of marker interfaces!
// This is perhaps overengineered, and all stems from the fact
// that we might not want the interfaces above to extend Op.
// Is there _ever_ a case where forcing a run() method is unwanted?
// If not, much of the following complexity can be eliminated.

public interface InputOp<I> extends Input<I>, Op { }
public interface OutputOp<O> extends Output<O>, Op { }
public interface InOutOp<I, O> extends InOut<I, O>, InputOp<I>, OutputOp<O> { }
public interface FunctionOp<I, O> extends Function<I, O>, InOutOp<I, O> { }
public interface ComputerOp<I, O> extends Computer<I, O>, InOutOp<I, O> {
  void setOutput(O output); // Maybe...
}
public interface InplaceOp<A> extends Inplace<A>, ComputerOp<A, A> { }
public interface HybridOp<I, O>
  extends Hybrid<I, O>, FunctionOp<I, O>, ComputerOp<I, O> { }

// And some partial abstract base classes, to illustrate the fields.
// Notice that none of the abstract classes below extend any other.

public abstract class AbstractFunctionOp<I, O> implements FunctionOp<I, O> {
  @Parameter(type = ItemIO.OUTPUT)
  private O output;
  @Parameter
  private I input;
  ...

  @Override
  public void run() {
    this.output = compute(getInput());
  }
}

public abstract class AbstractComputerOp<I, O> implements ComputerOp<I, O> {
  @Parameter(type = ItemIO.BOTH)
  private O output;
  @Parameter
  private I input;

  @Override
  public void run() {
    compute(getInput(), getOutput());
  }
  ...
}

public abstract class AbstractInplaceOp<A> implements InplaceOp<A> {
  @Parameter(type = ItemIO.BOTH)
  private A arg;
  ...
}

public abstract class AbstractHybridOp<I, O> implements HybridOp<I, O> {
  @Parameter(type = ItemIO.BOTH, required = false)
  private O output;
  @Parameter
  private I input;

  @Override
  public void run() {
    compute(getInput(), getOutput());
  }
  @Override
  public O compute(final I input) {
    final O output = createOutput(input);
    compute(input, output);
    this.output = output;
    return output;
  }
  ...
}
```
The big question is: do we need interface type hierarchies which are separate from `Op`? Or is OK if all of these interfaces are always subtypes of `Op`? In other words: is it OK for `run()` to be forced on every downstream type? I ask because I recall someone asking me at the last hackathon whether it was possible to utilize some of these types without requiring to implement the `run()` method. The design above achieves that, but at a substantial complexity cost.

So, assuming you like this general design, our options are:
1. Keep the separate shadowed `Op` type hierarchy as above.
2. Just make everything extend `Op`.
3. Keep the `Op`-free interfaces, but merge the `Op` interface and abstract class hierarchies; e.g., no `InplaceOp` interface but instead an abstract `InplaceOp` class.
4. Some fourth option that hasn't occurred to me.

The last thing is that the above design ignores the `Threadable` interface. Thoughts on where that would best fit in are welcome.

**Comment by ctrueden** [comment]
I'm going to flesh this out on a topic branch using option 3. So e.g. there will be `Function` which does not extend `Op`, and then `public abstract FunctionOp<I, O> implements Function<I, O>, Op`. This violates the "abstract class are prefixed with `Abstract`" rule, but there are other places in the ImageJ software stack that violate this for readability and convenience; e.g., [ContextCommand](https://github.com/scijava/scijava-common/blob/scijava-common-2.44.0/src/main/java/org/scijava/command/ContextCommand.java).

**Comment by ctrueden** [comment]
Worked started on the [function-redesign](https://github.com/imagej/imagej-ops/compare/function-redesign) branch. Doesn't compile yet. Will file a PR for review once all tests pass.

**Comment by hinerm** [comment]
My thoughts after talking with @ctrueden:

* I like the renames
* I think we should just have `Op`-based interfaces, e.g. `ComputerOp`, `FunctionOp`. If you want a `Function` that's not an `Op`... use Java 8? Otherwise, with these abstract classes the `run` method seems like it just delegates to the appropriate operation so it doesn't seem like a huge burden.
* Remove `Converter` from these hierarchies
* Rename `Input` and `Output` to `InputOp`, `OutputOp`  probably
* Move `InputOp`, `OutputOp`, `Threadable` to parents of `ComptuerOp`, `FunctionOp`, etc... hierarchy.

**Comment by ctrueden** [comment]
Thanks @hinerm.

Branch updated to follow option 2 above, as you suggest.

So there is `FunctionOp`, `ComputerOp`, `InplaceOp` and `HybridOp`. But no interfaces that are not `Op`s. An then each of those has an abstract base class as usual.

Remaining problems as of this writing:
* 9 compile errors, all in the `map` package.
* Weirdness with `Output` and `OutputOp` being two separate interfaces. I'd like to purge `setOutput(O)` from the API contract as requested, but a couple of `Map` implementations currently use it. But they may not actually need it—I need to study the `Map` ops more to understand them better in order to fix properly.

I'm still torn on whether we might want standalone `Function` and `Computer` interfaces, that do not extend `Op` or `Threadable`. But YAGNI, I guess. Unless @dietzc has a use case for it?

**Comment by dietzc** [comment]
> hinerm: If you want a Function that's not an Op... use Java 8? Otherwise, with these abstract classes the run method seems like it just delegates to the appropriate operation so it doesn't seem like a huge burden.

What we certainly also want, is that every `FunctionOp` is also a Java 8 `Function` (for lambda, streams etc).

> I'm still torn on whether we might want standalone Function and Computer interfaces, that do not extend Op or Threadable. But YAGNI, I guess. Unless @dietzc has a use case for it?

Actually, I don't see the advantage of each `Function` being an `Op`, besides that we have less interfaces. However, I also don't see the disadvantage at the moment, or I can't think of a use-case in `Op`s which would require a `Function` which is not an `Op`. So I don't know. As far as I understand, we could add non-op interfaces later anyway?! 

One thing which might be interesting, is that `Op` does not need to have a `run` method or the other way round, that the whole matching, discovering of `Ops` etc., does not work on `Op` level, rather on `Plugins`.

**Comment by ctrueden** [comment]
> I don't see the advantage of each `Function` being an `Op`, besides that we have less interfaces.

Right, this is actually a big advantage. Having `Function` _and_ `FunctionOp` is confusing for new developers trying to understand the API.

> I also don't see the disadvantage at the moment

Yeah, me either.

> As far as I understand, we could add non-op interfaces later anyway?!

Sure, we could. So we'll keep these core interfaces extending `Op` for now, then! Thanks for the feedback.

> One thing which might be interesting, is that `Op` does not need to have a `run` method or the other way round, that the whole matching, discovering of `Ops` etc., does not work on `Op` level, rather on `Plugins`.

I like the idea that any `Op` someone creates is automatically a `Command`, which can optionally have a `menuPath` and hence be available. But I don't think I understand your proposal. If you think a change to the design at such a fundamental level could honestly be worth the time investment, feel free to elaborate (maybe in a new issue?) and we can pursue it.

**Comment by ctrueden** [comment]
All right, I think 53e1505610ae366b6c7d12d2519b2a51c92535ed finally does the job. It's a big one, and I will rewrite it at least one more time just to flesh out the commit message properly. Ideally it should be split up, but it may be too involved, so pragmatically I may just leave it as one commit with a bullet list of what it accomplishes.

**Comment by dietzc** [comment]
> I like the idea that any Op someone creates is automatically a Command, which can optionally have a menuPath and hence be available to application end users. But I don't think I understand your proposal. If you think a change to the design at such a fundamental level could honestly be worth the time investment, feel free to elaborate (maybe in a new issue?) and we can pursue it.

I should have put it the other way round: It would be amazing (in the far future) if we could generalize all the parameter matching and `Op` discovery mechanism such that it works with arbitrary SciJava Plugins. In many situations I would have loved to have a mechanism like: Give me the `Plugin` with these parameters which has the highest priority. But this is really not too urgent.

**Comment by dietzc** [comment]
> All right, I think 53e1505 finally does the job. It's a big one, and I will rewrite it at least one more time just to flesh out the commit message properly. Ideally it should be split up, but it may be too involved, so pragmatically I may just leave it as one commit with a bullet list of what it accomplishes.

Amazing @ctrueden. Thank you so much! This rocks!

**Comment by ctrueden** [comment]
I ended up splitting apart that huge commit properly, and filing PR #165. When it merges, this issue will close out. And the end result relative to the original request is that the `Output` interface will no longer have a `setOutput(O)` method in its contract—nothing needs it.

**Comment by dietzc** [comment]
one argument against `createOutput` in `Function`: Sometimes there is no output object (e.g. with views). So we made a great decision :+1:

**Comment by ctrueden** [comment]
@axtimwalde In case you are still curious about why `FunctionOp` and `ComputerOp` are rather fat `Op` subinterfaces (with `run`, `getInput`, `getOutput`, etc.) instead of being as thin as possible: here is the discussion from July. And also in #165.
