### ISSUE TITLE
Enhance Map Ops

### ISSUE THREAD

**Issue by LeonYang5114** [imagej/imagej-ops#288]
With binary Ops, we would be able to implement binary Maps, which take two input (with or without an output), a BinaryOp, and do operations based on the two inputs. This will be useful for doing math between two images. These Maps would take the place of some MathOps that are auto generated (see `IterableIntervalToImage`, and `RandomAccessibleIntervalToIterableInterval`).

I also suggest to have some MapOps that work on Images of specific native types in order to have better performance. This could be done by migrating the existing code in e.g. `ConstantToArrayImageP`. When the Map is iterating the internal data structure of the Image, a `T extends RealType<T>` temporal variable should be created to support `ComputerOp` or `InplaceOp` operations. By this way, we could support more operations but possibly not losing much performance. This should be benchmarked carefully.

**Comment by dietzc** [comment]
great that you take a look at our `Map` ops. Especially the implementations based on native arrays will speed-up things dramatically. With `BinaryMap`s also a different aspect has to be considered: We didn't have a `MapFunction` / `MapConstant`, yet (we could/should add this, like: Multiply image with 15 etc). For `BinaryOp`s we want to have `MapBinaryFunctionOp`, which e.g. adds up to images and creates an output for you and of course a `MapBinaryComputerOp`. of course both parallel.

> I also suggest to have some `MapOp`s that work on Images of specific native types in order to have better performance. 

How would this be faster? If you mean to access the native, underlying array directly, then we have two options: (a) we implement `BinaryFunctionOp`s which operate on native types and then can then be used as a worker in a special `MapOp` which e.g. operates on `byte[]` or whatever. However, for maximum efficiency (and as we don't want to rely on the JIT), we may want to avoid the `compute` call.  Therefore we could (b) implement e.g. a special `Add` which operates on arrays (as we do it already with auto-generated code). 

> ConstantToArrayImageP and IterableIntervalToImage 

Just concerning naming of `Op`s: The word `Image` or `Img` shouldn't ever be part of an op-name,  from my point of view, except if we really, really need an `Img`. Usually we can always operate on `IterableInterval`s, `RAI`s, something which extends both of them or e.g. native `Array`s. Please rename whenever possible! If we use the word image (e.g. if we refer to `ArrayImg` which also should only be the case in a `Converter`), the we should stick to `Img` instead of `Image`.
Cheers,

Christian

**Comment by dietzc** [comment]
one more comment: I think a good way to go is to first create the very, very general `Map`s and `MapBinary`s variants based on `IterableInterval`s, `RandomAccessibleInterval`s etc. in their single/multithreaded versions. They will call each other if the `IterationOrder's do not match etc. For exmaple one `Op` can accepts and handles (sets them e.g. to `FlatIterationOrder` using `View`s different `IterationOrder's, the other can't. Then we can write tests and then optimize as much as possible! 

By the way: if this is what is already happening forget all I wrote ;-) I lost a bit the overview what is going on.

**Comment by dietzc** [comment]
more on this very important topic: http://forum.imagej.net/t/suggestions-for-iitorai-computerops/415/9?u=dietzc

**Comment by LeonYang5114** [comment]
@dietzc Thanks for your detailed comment!

I did think about using `FunctionOp` before. But since the internal type is almost always primitive, how can we pass any `byte` etc. to the `FunctionOp`? I think if we want to use `SpecialOp` to `computer` on the internal data structure, we still need some kind of temporary variable to store the primitive value of each pixel.

By faster I mean that Mapping the `byte[]` etc. would be faster than Mapping the high-level data structure e.g. RAI or `IterableInterval`. I come up with this idea because I think we might want to do more than just add/mul/sub/div on an Image. If we want to do more than that, we need to support `SpecialOp`s. Then the (only) way to make Mapping faster while keeping `SpecialOp` might be iterating over internal data structure.

And I think you are right about removing the calls to `compute()` in Map, but only for some limited operations (add/sub/mul/div). This will make the Map super fast, as the benchmark shows. 

Therefore, for an operation on an Image, we have three levels of operation selection:
1. if the data structure of the image is not known, use the most general Map (II2RAI etc.)
2. if the operation is complicated, use Map on internal data structure but still support `SpecialOp`
3. if the operation is simple, use the Op provided by the operation, which do not call `compute` at all

For the naming, I will fix them soon. One problem about naming has bothered me for a while. If we want to do operation between 2 images, then we will have this list of classes:
1. `Iterable2Iterable`
2. `IterableInterval2InterableInterval`
3. `IterableInterval2RAI`
4. `RAI2IterableInterval` (3 and 4 are exactly the same! just for users convenience?)
5. `IterableInplace`
and their parallel versions! Oh I just recognize that we do not have `MapRAIToIterableIntervalParallal` in our Map package. Now I want to have some `BinaryOp`s that work on 2 or 3 images, which potentially might have all different types! I am totally lost about how to create all those names to capture all combinations of different images types. Do you have any idea?

**Comment by dietzc** [comment]
>I did think about using FunctionOp before. But since the internal type is almost always primitive, how can we pass any byte etc. to the FunctionOp? I think if we want to use SpecialOp to computer on the internal data structure, we still need some kind of temporary variable to store the primitive value of each pixel.

Why `SpecialOp`? Unary case:  Using `FunctionOp` can only be done if the `FunctionOp` takes a `Type` as an input and give us another `Type` as an output, which we can set in the resulting image. And if the underlying type is primitive we actually only can use `FunctionOp` rather than `ComputeOp` as we can't pass a reference on the type. Binary case: Here we can find more examples for `BinaryFunctionOp`s. and `MapBinaryFunctionOp`. Actually always if I don't want to create the output on my  own. Most of such `Op`s can be `HybridOp`s in their general implementation.

> By faster I mean that Mapping the byte[] etc. would be faster than Mapping the high-level data structure e.g. RAI or IterableInterval. I come up with this idea because I think we might want to do more than just add/mul/sub/div on an Image. If we want to do more than that, we need to support SpecialOps. Then the (only) way to make Mapping faster while keeping SpecialOp might be iterating over internal data structure.

Agreed. Just two comments: 1. I don't understand what you want to do with the `SpecialOp`? You have to use `FunctionOp` or `ComputerOp` in either case, unary or binary. 2. Why can't we offer super fast versions of more complicated `Op`s based on the native types? Maybe we can't auto-generate them, but we can offer them. If we don't offer them, the user will fall back to the ones based on `Map`. 

> And I think you are right about removing the calls to compute() in Map, but only for some limited operations (add/sub/mul/div). 

I'm not suggesting that we remove any `compute` in a `Map`. I say, that we don't use `Map` at all in some very special, very fast implementations.

> Now I want to have some BinaryOps that work on 2 or 3 images, which potentially might have all different types! I am totally lost about how to create all those names to capture all combinations of different images types. Do you have any idea?

Honestly, no ;-) I think we really have to explicitly model this. Maybe these `Op`s can base on each other (call each other). Another idea might be that we only offer `Map` for `IterableInterval` to `IterableInterval` and (somehow) `Converter`s take care about the conversion of the inputs such that they have the correct iteration order. This would be nice, because we wouldn't require the `Map` to be smart and put the logic somewhere else. However, this is not possible at the moment: (a) we can explicitly enforce some input-type in the `Map` which say that two inputs must have the same `IterationOrder` and therefore `Converter`s can't convert. and (b) we should be smart when converting,  i.e. we shouldn't always just convert `RAI`s with `Views.flatIterationOrder(....)` because maybe one of the inputs has a different `IterationOrder` which can be iterated very fast and we only have to perform the expensive calculation on the second input. @ctrueden thoughts? From my point of view we should offer `Op`s which assure `IterationOrder` and these `Op`s are used inside the `Map`s which we have to create (all of them, I think, ... sorry).

**Comment by LeonYang5114** [comment]
@dietzc Sorry for not being specific. I mentioned `SpecialOp` just because I am not sure whether should I use `ComputerOp` or `FunctionOp` and being fuzzy. 

> Why can't we offer super fast versions of more complicated Ops based on the native types? Maybe we can't auto-generate them, but we can offer them. If we don't offer them, the user will fall back to the ones based on Map.

Do you suggest that we should have more super fast operations between images than just add/sub/mul/div? My concern is the proliferation of potentially not often used Ops. As mentioned above, each operator needs about 10 signatures, and there are many operators (and, or, not, xor, sqr, sqrt...)!

By the way, I think making the convert service smarter might be a better solution, but I am not quite familiar with that. Do we already have a way to wrap an RAI to an `IterableInterval` with a specific `IterationOrder`? (more than just flatten it!) If we can do that, then we can safely have only one signature `IterableInterval2IntervalInterval` in the Map and other Ops.

**Comment by LeonYang5114** [comment]
@dietzc One problem of having all those different RAI and II combinations in the namespace is that, `ops.map(someArrayImg, anotherArrayImg, someComputerOp)` will never work as `The method map(Object[]) is ambiguous for the type OpService` (as long as the typing of the three parameters are consistent). Things will be much much better if the convert service can handle all that.

**Comment by ctrueden** [comment]
My intuition is that writing a map implementation for a primitive type such as `byte[]` that works element-wise would not be a time savings, due to boxing and unboxing.

We could of course have ops that operate directly between two primitive-array-backed images, e.g. `ArrayImg<ByteType, ByteArray>` + `ArrayImg<ByteType, ByteArray>` but such combinations would be extremely many. There are also issues with signedness, lossy conversion, and likely other subtleties. I would rather wait on this work for the time being. We can revisit later as needed for performance.
