### ISSUE TITLE
HybridOps vs FunctionViaComputer

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#303]
Hi all (especially @ctrueden),

I was looking at the current design of `FunctionOp`, `HybridOp`, `ComputerOp` etc. I also noticed the wrappers, especially `FunctionViaComputer` and I have the following questions/comments: 

* Is there any reason to maintain `AbstractHybridOp`, besides convenience reasons? Actually, we could always wrap a `ComputerOp` into a `FunctionOp` using `FunctionViaComputer`. 
* One advantage of using `FunctionViaComputer` instead of `HybridOp` is that, we can actually have method signatures with optional input parameters without having to specify the `out` of the `Hybrid`, which is not possible in the case of `HybridOp`.
* I'm not really sure how we can automated this such that for each suited `ComputerOp`(which may also implement some special marker interface/annotation) a `FuntionOp` will automatically be created and the the namespace tests can handle the wrapping. However, I'm somehow pretty sure it's possible and involves the redesign of `Create`. If we can automate this, we could totally get rid of `HybridOp`.

Does this make sense?

Christian

**Comment by ctrueden** [comment]
> Is there any reason to maintain AbstractHybridOp, besides convenience reasons? Actually, we could always wrap a `ComputerOp` into a `FunctionOp` using `FunctionViaComputer`.

Using `AbstractHybridOp` allows you to have one Java class instead of two when you need to implement an algorithm as both a computer and a function. I'm not sure exactly how many lines of boilerplate code it saves though. Perhaps not many, if you structured your two-class version with the function as a static inner class. Still, this might is more complex to understand for people new to Ops.

> One advantage of using `FunctionViaComputer` instead of `HybridOp` is that, we can actually have method signatures with optional input parameters without having to specify the `out` of the `Hybrid`, which is not possible in the case of `HybridOp`.

Yep, true.

> I'm not really sure how we can automated this such that for each suited `ComputerOp`(which may also implement some special marker interface/annotation) a `FuntionOp` will automatically be created and the the namespace tests can handle the wrapping.

I think we are quite far from supporting that kind of autogeneration. It strikes me as similar to the chained ops in general. It is not hard for us to do it manually for the operations which support it. I think it would cost a lot of development time to craft some clever infrastructural solution, and it would not serve all our use cases anyway, and it would be non-standard, and potentially fragile, and more complex for new people, and... so let's not do it.

**Comment by ctrueden** [comment]
So, I'll assume the main point of this issue is to decide whether to keep the `(Nullary|Unary|Binary)HybridOp` classes. We can discuss at the hackathon, and remove them if we decide they are no longer necessary.

**Comment by ctrueden** [comment]
I decided to keep them. And actually there are more now. Yay.
