### ISSUE TITLE
Trigger Jenkins builds for PRs 

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-ops#347]
It would be awesome to have Jenkins run on PRs and properly integrate it with the [GitHub Commit Status API](https://developer.github.com/v3/repos/statuses/) as implemented by [ghprb](https://github.com/janinko/ghprb).

Is there any obvious reasons to not implement this apart from the load increase on the build workers?

**Comment by gab1one** [comment]
I think this is a great idea, we could even couple that with a [sonarqube](http://www.sonarqube.org/) installation with the [github plugin](http://www.sonarqube.org/github-pull-request-analysis-helps-fix-the-leak/) we could get feedback on technical debt leaks before we merge the code.

**Comment by stelfrich** [comment]
@gab1one I like the idea! Do you know how well the current code base plays with sonarqube?

**Comment by gab1one** [comment]
Rather well, I have not set up a permanent server so there are some false positives (especially regarding logging) but that could be fixed rather easily in a permanent setup
![screen shot 2016-02-12 at 10 34 12 am](https://cloud.githubusercontent.com/assets/1938154/13013234/3ab15faa-d174-11e5-832e-f689d6c16277.png)
.

**Comment by gab1one** [comment]
This article describes very well why we should do the checks before merging, to ensure consistent code quality: http://www.sonarqube.org/water-leak-changes-the-game-for-technical-debt-management/.

**Comment by ctrueden** [comment]
In principle, I am fine with more automated checks of all PRs. However, I would want to do it across the board for _all_ PRs. Not just ImageJ Ops. This issue applies to the entire SciJava software stack.

The reasons we haven't already set it up:

1) It is work. And it adds substantial complexity, which must be documented somewhere so that maintenance later is not troublesome. As part of this work, we may want to migrate to Travis for all of our "regular ol' master builds" and keep the ImageJ Jenkins only for "weird" builds of things besides just the latest master. That would have many advantages, including reducing our dev server's workload, reducing the impact of any downtime, and most importantly provide the community with an extensible model for their own projects that do not require use of the central ImageJ Jenkins.

2) I firmly believe in [rapid iteration](http://blog.codinghorror.com/boyds-law-of-iteration/). If master breaks, push again to fix it. Yes, we want master to be "release ready", and we do not want to merge crap with master. But I also do not want every PR held up for weeks while it is intensely scrutinized. There is a balance. It needs to be possible to merge things to master in a matter of minutes. So whatever automation we have here cannot take an hour to run, or else it will bog down our process.

So what do others think? Switch to Travis for basic builds? And configure it to do merge builds as well? Sonarqube is fine too, but it is even more work upfront which will impose additional occasional bureaucracy (false positives etc. as @gab1one mentions).

**Comment by ctrueden** [comment]
By the way, this would be a great project for @aneevel—except that he has a few other critical priority things to finish first...

**Comment by gab1one** [comment]
sonarqube analysis for imagej-ops takes about 1:30 minutes, so there is no issue with it impacting performance.

Travis does has a much longer roundtrip time than our jenkins, in some cases up to an hour so that would not be that ideal for rapid development.

If we add a ``travis.yml`` file to our projects 3rd party contributors can activate travis for their forks, independently of our decision if we run jenkins on pull requests or not.

The additional burocracy should be rather minimal, besides of the initial effort of sorting through the

**Comment by stelfrich** [comment]
> Travis does has a much longer roundtrip time than our Jenkins, in some cases up to an hour so that would not be that ideal for rapid development.

I find that hard to believe, somehow. Do you know anything about where that time was spent, @gab1one? Is it waiting for the build to start, or time spent in the build?

> This issue applies to the entire SciJava software stack.

Nonetheless, I feel that Ops could be a good place to start. Maybe just start with a _travis_ branch while keeping the rest untouched? It might take some time to come up with a configuration that's appropriate.

To add to the aforementioned points: what about the house keeping tasks that Jenkins is used for in the SciJava stack - Javadocs, release packaging and deployment. What about Travis in that context?

**Comment by gab1one** [comment]
@stelfrich The waiting time for the builds was rather long the day I tested it, I looked at it again today and there was about a one minute delay between my commit and the build starting. The build itself takes about 2:30 minutes.

**Comment by stelfrich** [comment]
> there was about a one minute delay between my commit and the build starting

I guess that would be acceptable for PRs and branches. Usually it takes some time for a second person to review the changes anyway, hence a delay of up to an hour seems alright. Plus, you could always checkout the PR and run tests locally.

**Comment by gab1one** [comment]
I created a pull request for travis support: #356

**Comment by stelfrich** [comment]
PRs are built by Travis CI as of https://github.com/imagej/imagej-ops/commit/d85c4204fc052ba8bf81df476e84d955d5f8aa7b.
