### ISSUE TITLE
Matching Problem?

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#353]
Hi @ctrueden,

I created a small test which shows a potential problem with the matching. The test is selfexplaining, however if you have any questions I'm happy to answer them.

https://github.com/imagej/imagej-ops/tree/matching_problem

Thanks,

Christian

**Comment by LeonYang5114** [comment]
This problem is already solved after the latest commits. But to answer the question, here are the reasons:

1. `Dimension` is not `Interval`, so it can only match `DefaultCreateImg`, which is fine.
2. matcher tries to match `CreateImgFromInterval` in the second case, which tries to a `DefaultCreatingImg` using the input (should be an `Interval` if it is not matched by class object, or null o/w). Since the class information is lost, the initialization fails.
3. If a null check is there (e.g. `input == null ? Interval.class : input`), the matching would be fine.

By the way, it is me that wrote the `initialize` code and forgot the do the null check :-P

**Comment by dietzc** [comment]
But `Interval extends Dimension`, so the matching should work, right?

**Comment by LeonYang5114** [comment]
Yes, it should work, as long as `CreateImgFromInterval` does a null check in the initialize method.

**Comment by dietzc** [comment]
Hi @LeonYang5114,  have a look at the example code which I provided in mentioned branch. It doesn't work with `Interval.class` but works fine for `Dimension.class`, so the `null` check can't be the reason or do I miss something obvious here? I try to find some time to debug this next week!

Thanks for your efforts!

Christian

**Comment by LeonYang5114** [comment]
I pushed a1d51d9 to your branch, which fixed the problem.

The problem is that the two lines of codes actually match with the different ops. If the `CreateImgFromInterval` op is removed, there will be no problem. Anyway, the problem has been fixed in the master branch.

**Comment by dietzc** [comment]
perfect. thanks
