### ISSUE TITLE
StackView op should reflect changes in imglib2

### ISSUE THREAD

**Issue by hanslovsky** [imagej/imagej-ops#495]
The interface of `Views.stack` and `StackView` in imglib2 has been relaxed as it did not allow to pass, for example, `List< Img< T > >` :
imglib/imglib2#156
imglib/imglib2#157

This should be reflected in the `StackView` op. I can add these changes once this update is part of an imglib2 release.

**Comment by ctrueden** [comment]
@gselzer See the `issue-495` branch for a start on this update.

**Comment by gselzer** [comment]
@ctrueden I believe that this issue should be fixed. I rebased this branch over master, which means that as of now it fails due to the conflict between the invert ops and the watershed tests. Once #542 is merged, I will rebase this branch over master again and make sure that the commit builds. Otherwise I believe this branch is ready for merge.
