### ISSUE TITLE
What is "net.imagej.ops.Ops"?

### ISSUE THREAD

**Issue by hijizhou** [imagej/imagej-ops#532]
Hi guys, many classes use this import: 
`import net.imagej.ops.Ops;`
I am wondering where this package is?  Is it really necessary?

Thanks.

**Comment by ctrueden** [comment]
Hi @hijizhou!

`net.imagej.ops.Ops` is the class housing all the marker interfaces. It is autogenerated during the `generate-sources` phase, so you'll find the source in `target/generated-sources/from-template/net/imagej/ops/Ops.java`. The template files which generate it can be found at `src/main/templates/net/imagej/ops/Ops.vm` and `src/main/templates/net/imagej/ops/Ops.list`.

As for whether it is "necessary"... depends what you mean by that? There are always different architectural decisions which could be made to restructure things. If you are asking about its _purpose_: the class houses all the type-safe marker interfaces, so that you can ask for ops by type rather than by name. These interfaces provide compile-time safety (e.g. if you ask for an `Ops.Filter.Gauss` then any ops returned will implement this interface, guaranteed). We also plan to use them in the future for inheritance in some cases for "sub-types" of ops: e.g. `Op.Transform.RotateView` (guaranteed to rotate an image _virtually on demand without copying_) will extend `Ops.Transform.rotate` (an op to rotate an image, but _might or might not make a copy of the samples_).

Happy to comment further if anything is still not clear!

**Comment by hijizhou** [comment]
Very impressive. Thanks for your detailed explanation, Curtis @ctrueden .  I got it now.
