### ISSUE TITLE
AbstractHandlerService isn't handling Generics

### ISSUE THREAD

**Issue by DanielSeebacher** [imagej/imagej-ops#93]
If the following code is run on the *geometric-features* branch a ```ClassCastException``` is thrown.

```java
    ops.run(AreaFeature.class, Arrays.asList(1, 2, 3));
```

There are different ways to calculate the area. The ```List<Integer>``` should be forwarded to an ```AbstractOutputFunction<Iterable<?>, ...>```, but somehow the ```List<Integer>``` is converted into a ```Polygon``` and then forwared to an ```AbstractOutputFunction<Polygon, ...>``` which has a higher priority.

It shouldn't be possible to create a ```Polygon``` from a ```List<Integer>```. The ```Polygon``` has only one private field, a ```List<RealPoint>```. But somehow this ```List<RealPoint>``` is replaced with a ```List<Integer>``` and a ```ClassCastException``` is thrown when the ```Polygon``` data is accessed.

I traced the error to the ```AbstractHandlerService```, which receives a ```ConversionRequest``` from ```List<Integer>``` to ```Polygon``` and decides that it can do that conversion.

**Comment by ctrueden** [comment]
The way the `ConvertService` currently works, it will ultimately attempt a conversion whenever the destination object type has a single-argument constructor that takes an instance of the source object type. In this case, the `Polygon(List<RealPoint> points)` is what causes that conversion to be attempted. (The conversion routine is too dumb right now to realize that the generics don't match. And improving it is difficult due to generics runtime erasure.)

Probably what needs to happen is to back off on that auto-wrapping-via-constructor heuristic, since it will sometimes cause problems in the future, in favor of only explicitly implemented `Converter` plugins. See also #54.

**Comment by ctrueden** [comment]
This will be solved by #15, which is a generally tricky issue, but solvable.
